apiVersion: v1
data:
  log_level: INFO
  busyxbox_check: |
    sleep 5
    uptime
kind: ConfigMap
metadata:
  name: log-config
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: test
      image: busybox:1.28
      command: ['sh', '-c', 'echo "The app is running!" && tail -f /dev/null']
      volumeMounts:
        - name: config-vol
          mountPath: /etc/config
  volumes:
    - name: config-vol
      configMap:
        name: log-config
        items:
          - key: log_level
            path: log_level
          - key: busyxbox_check
            path: busyxbox_check
