apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
      medium: Memory # default is disk
      # sizeLimit: 1Gi #can be only set for disk medium. If the SizeMemoryBackedVolumes feature gate is enabled, you can specify a size for memory backed volumes
