---
apiVersion: v1
kind: Pod
metadata:
  name: k8s-labs
spec:
  containers:
    - name: k8s-labs
      image: nginx:latest
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: k8s-labs
