apiVersion: v1
data:
  config: |
    {
      "apiVersion": "v1",
      "kind": "ConfigMap",
      "metadata": {
        "name": "myconfigmap",
        "labels": {
          "name": "myconfigmap"
        }
      }
    }
kind: ConfigMap
metadata:
  name: myconfigmap
---
apiVersion: v1
stringData:
  username: rbalman
kind: Secret
metadata:
  name: mysecret
---
apiVersion: v1
kind: Pod
metadata:
  name: projected-pod
  labels:
    app: projected-volume
spec:
  containers:
  - name: container-test
    image: busybox:1.28
    command: ["sleep", "3600"]
    volumeMounts:
    - name: all-in-one
      mountPath: "/projected-volume"
      readOnly: true
  volumes:
  - name: all-in-one
    projected:
      sources:
      - secret:
          name: mysecret
          items:
            - key: username
              path: my-group/my-username
      - downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
            - path: "cpu_limit"
              resourceFieldRef:
                containerName: container-test
                resource: limits.cpu
      - configMap:
          name: myconfigmap
          items:
            - key: config
              path: my-group/my-config
