---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-labs101
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: k8s-labs101
