apiVersion: v1
stringData:
  username: mandip
  password: topSecret
  token: dG9wU2VjcmV0Cg==
kind: Secret
metadata:
  name: top-secret
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: busybox
      image: busybox:1.28
      command: ['sh', '-c', 'echo "The app is running with secret!" && tail -f /dev/null']
      volumeMounts:
        - name: secret-vol
          mountPath: /etc/top
  volumes:
    - name: secret-vol
      secret:
        secretName: top-secret
        items:
          - key: username
            path: username
          - key: password
            path: password
          - key: token
            path: token