apiVersion: v1
data:
  top: U2VjcmV0
kind: Secret
metadata:
  name: top-secret
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: busybox
      image: busybox:1.28
      command: ['sh', '-c', 'echo "The app is running with secret!" && tail -f /dev/null']
      volumeMounts:
        - name: secret-vol
          mountPath: /etc/top
  volumes:
    - name: secret-vol
      secret:
        secretName: top-secret
        items:
          - key: top
            path: secret