---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: k8s-lab
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    env:
      - name: API_KEY
        valueFrom:
          configMapKeyRef:
            name: game-demo
            key: API_KEY
      - name: LAB_NAME
        valueFrom:
          configMapKeyRef:
            name: game-demo
            key: LAB_NAME
      - name: LOG_LEVEL
        valueFrom:
          configMapKeyRef:
            name: game-demo
            key: LOG_LEVEL
