---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-labs
data:
  config.yaml: |
    logging:
      level: info
    server:
      port: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: k8s-labs
spec:
  containers:
  - name: k8s-labs-pod
    image: nginx:1.14.2
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: k8s-labs
