---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-101
  labels:
    app: k8s-lab
spec:
  containers:
  - name: nginx-101
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    env:
      - name: password
        valueFrom:
          secretKeyRef:
            name: k8s-labs-secrets
            key: password
