---
apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
  labels:
    app: k8s-lab
spec:
  containers:
  - name: nginx-101
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    volumeMounts:
    - name: secret-volume
      mountPath: /secrets
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: k8s-labs-secrets
      items:
      - key: username
        path: username
